Added English editorial for LightOj 1428 (Melody Comparison)
lightoj-dev/problem-tutorials pull request #12
Opened 2020-11-15 16:34 UTC by zarif98sjs

2020-11-15 20:41 UTC, faiyaz26 requested changes

2020-11-15 20:41 UTC, faiyaz26 commented on 1428/en.md
> +<h1 align="center"> <b>LightOj 1428 (Melody Comparison) </b> </h1>
Add the title like this: https://github.com/lightoj-dev/problem-tutorials/pull/11/files#diff-49d89fcefb3733849902cae167206bfef3d2d2fa1569a2abcc5b303e53f828b9R1

2020-11-15 20:41 UTC, faiyaz26 commented on 1428/en.md
> +# **Tags**
use header2 on markdown, its double hash

2020-11-15 20:41 UTC, faiyaz26 commented on 1428/en.md
> +**`string`** , **`suffix array`** , **`binary search`** , **`kmp`**
dont need to make it bold

2020-11-15 20:41 UTC, faiyaz26 commented on 1428/en.md
> +
Explain the problem a bit, what the problem is asking

2020-11-15 20:41 UTC, faiyaz26 commented on 1428/en.md
> +# **Idea**
Only for the problem title use header1 markdown, for other header 2 and so on

2020-11-16 03:54 UTC, zarif98sjs commented
Change requests are resolved now . Please check if everything is okay now .

2020-11-16 09:55 UTC, merged