bangla and english tutorial added on 1417
lightoj-dev/problem-tutorials pull request #278
Opened 2021-05-27 20:18 UTC by subhashiscse

2021-05-28 02:33 UTC, rebornplusplus requested changes

2021-05-28 02:33 UTC, rebornplusplus commented on 1417/en.md
> +4 5 - 4th person can send mail to 5th person
* Try including a drawing of the graph. https://csacademy.com/app/graph_editor/
* Markdown makes these 5 lines into 1, resulting in poor readability. Use `<br/>` I guess.

2021-05-28 02:33 UTC, rebornplusplus commented on 1417/bn.md
> +৪ ৫ - ৪র্থ জন ৫ম জনকে মেইল পাঠাতে পারবে
* Try including a drawing of the graph. https://csacademy.com/app/graph_editor/
* Markdown makes these 5 lines into 1, resulting in poor readability. Use `<br/>` I guess.

2021-05-28 16:20 UTC, subhashiscse commented
I add the graph image.Can you please check again?

2021-05-28 17:00 UTC, rebornplusplus commented
* You forgot to link the image in `en.md`.
* Maybe you should crop the image a little bit. It's quite big. (But you can ignore this.)

2021-05-28 17:08 UTC, subhashiscse commented
Yeah my mistake to add the image link in en.md.
Now add it and image crop

2021-05-29 06:00 UTC, rebornplusplus approved these changes
Everything looks okay. Good work!

2021-05-29 06:05 UTC, merged