bangla and english tutorial added
lightoj-dev/problem-tutorials pull request #281
Opened 2021-05-28 16:41 UTC by subhashiscse

2021-05-28 16:51 UTC, subhashiscse commented
Explanation added with a new branch.

2021-05-29 06:14 UTC, subhashiscse commented
@rebornplusplus   can you please check my other tutorial?

2021-05-29 13:21 UTC, subhashiscse commented
This tutorial have been updated with explanation. You may check again now. @rebornplusplus

2021-05-29 14:43 UTC, rebornplusplus requested changes
Your solution has a bug. Consider this input:
```
1
2
9 10
```
Output should be 9. Produces 1.

2021-05-29 14:45 UTC, rebornplusplus commented
@jan876 I think 1425 has weak dataset. Consider this submission: https://lightoj.com/submission/2079589

2021-05-29 17:39 UTC, subhashiscse commented
After updating the data set may be my first code is not working.
Now i update the code and description. It works fine.
Please check now.

2021-05-29 18:35 UTC, rebornplusplus requested changes
Binary search was quite alright actually. You just had to mind the first step as well. Anyway, now the algorithm has a better runtime. Kudos.

2021-05-29 18:35 UTC, rebornplusplus commented on 1425/en.md
> +#define fr(i1,m) for(int i1=0;i1<m;i1++)
Can you please remove this define? Improves readability.

2021-05-29 18:45 UTC, subhashiscse commented
Solved. Now i think its better to user readable.
Thanx a lot.

2021-05-29 19:09 UTC, rebornplusplus approved these changes
Thank you for your contribution.

2021-05-29 19:10 UTC, merged

2021-05-29 19:19 UTC, subhashiscse commented
Hello brother,
Tutorial is not visible here.When it'll visible?
https://lightoj.com/problem/the-monkey-and-the-oiled-bamb

2021-05-29 20:05 UTC, rebornplusplus commented
Dunno. The process is manual I think. Usually takes a day or two.