1087
lightoj-dev/problem-tutorials pull request #30
Opened 2020-11-25 17:49 UTC by tstanvir

Add 1087 - Diablo tutorial

2020-11-25 18:27 UTC, Tahanima requested changes
Hi, please resolve all the requested changes. Also, make sure to change your bn.md file accordingly as well.

2020-11-25 18:27 UTC, Tahanima commented on 1087/en.md
> +# [http://lightoj.com/volume_showproblem.php?problem=1087](http://lightoj.com/volume_showproblem.php?problem=1087 "1087 - Diablo") #
Please add the problem title in this format - https://github.com/lightoj-dev/problem-tutorials/pull/11/files#diff-49d89fcefb3733849902cae167206bfef3d2d2fa1569a2abcc5b303e53f828b9R1

2020-11-25 18:27 UTC, Tahanima commented on 1087/en.md
> +**Code: C++:**
Please use the appropriate syntax for code blocks. Here is a reference - https://github.com/lightoj-dev/problem-tutorials/pull/22/files#diff-8b373101a9727d57ad4dc62e959037a667fd41e97ba2f9e1fa3cf56d2bdea2dbR22

2020-11-25 18:27 UTC, Tahanima commented on 1087/en.md
> +
Please remove the unnecessary blank line.

2020-11-25 18:27 UTC, Tahanima commented on 1087/en.md
> +
Please fix all your line breaks. Here's a reference - https://markdown-guide.readthedocs.io/en/latest/basics.html#line-return

2020-11-25 19:43 UTC, tstanvir commented
hi , i have resolved the changes you have asked for . Can you recheck and let me know that it is okay , please ? Thanks.

2020-11-26 05:24 UTC, Tahanima commented
Hi
1. You haven't followed the title style and format I've asked for.
2. Your writing has a mix of capital and small letters where it is expected to use capital letter. It looks very informal. Please fix that.
3. There's still unnecessary blank lines in your code.
4. Also, please follow the style we are using for headings such as **C++** and **Java**.
5. Your code is missing C++ header file, main function and some pre-requisites to get the code accepted. I would suggest you to include these missing parts.
6. You have mentioned about the use of BIT to solve the problem but you haven't explained the algorithm itself. Please provide link to a tutorial which explains this algorithm.

Please resolve the above mentioned issues.

2020-11-26 11:17 UTC, tstanvir commented
Hello, sorry for the inconvenience. I've rechecked all the points you mentioned. Will you please let me know if there is further changes I need to resolve ? Thanks again.

2020-11-26 13:20 UTC, Tahanima commented
Hi, 
Thank you for your contribution.

2020-11-26 13:20 UTC, merged