Tutorial for LOJ-1266
lightoj-dev/problem-tutorials pull request #364
Opened 2022-01-23 12:05 UTC by qubits-fan

2022-01-23 12:06 UTC, qubits-fan commented
Tutorial for the problem LOJ 1266 . Please update the solution if one found another efficient approach.

2022-01-24 15:02 UTC, showrav-ansary requested changes

2022-01-24 15:02 UTC, showrav-ansary commented on 1266/en.md
> +<a here="https://cp-algorithms.com/data_structures/fenwick.html" target="_blank">
The anchor tag is incorrect. The link is not showing up in the paragraph. It should be `href` instead of `here`.

2022-01-24 15:02 UTC, showrav-ansary commented on 1266/en.md
> +    // Frist we have initialized a Grid of 1000X1000
`Frist` is spelled incorrectly.

2022-05-25 22:54 UTC, faiyaz26 commented
@qubits-fan could you resolve the comments and update the pull request? Thanks for the contribution.

2022-06-25 12:10 UTC, closed without merging