Added Bangla Tutorial for Circle in Square
lightoj-dev/problem-tutorials pull request #411
Opened 2022-11-29 07:41 UTC by walleeva2018

2022-11-29 08:00 UTC, walleeva2018 commented
Hello Sir, Is my way of creating PR is okay? If so i will create PRs for rest of my solutions in similar manner

2022-11-29 12:15 UTC, rebornplusplus commented
This PR looks good enough. Although there are multiple commits regarding other files, they will be squashed when the PR gets merged. So that's not a biggie. 

I will review the tutorial soon.

2022-11-29 18:12 UTC, rebornplusplus requested changes
Good work. Follow the reviews and propose appropriate changes again.

2022-11-29 18:12 UTC, rebornplusplus commented on 1022/bn.md
> +২ [বর্গের ক্ষেত্রফল ] (https://www.khanacademy.org/math/geometry-home/geometry-area-perimeter/geometry-perimeter/v/perimeter-and-area-basics)
Make this a list. Prefix each line with a dash (-) or an asterisk (*).

2022-11-29 18:12 UTC, rebornplusplus commented on 1022/bn.md
> +২ [বর্গের ক্ষেত্রফল ] (https://www.khanacademy.org/math/geometry-home/geometry-area-perimeter/geometry-perimeter/v/perimeter-and-area-basics)
The link doesn't render as intended. I think because of spaces between ] and (.

2022-11-29 18:12 UTC, rebornplusplus commented on 1022/bn.md
> +ধাপ -৩ a - b ই হল আমাদের কাঙ্ক্ষিত এলাকা যা চিত্রের মাঝে সহজে ই বোঝা যাচ্ছে
Make this a list as well. Prefix each line with a dash (-) or an asterisk (*).

2022-11-29 18:12 UTC, rebornplusplus commented on 1022/bn.md
> +উত্তর প্রদর্শনের সময় ০.০০০০০০০০০৯ যোগ করতে হবে ( যদিও এইটা ছাড়া ACC পাওয়া যায় )
You don't need to add anything. Remove this, both from here and from source code.

2022-11-29 18:12 UTC, rebornplusplus commented on 1022/bn.md
> +#define ll long long int
Lose the defines. Add an empty line here instead.

2022-11-29 18:12 UTC, rebornplusplus commented on 1022/bn.md
> +}
Name the variables as they are in the problem statement and as you defined it in your explanation. `r` should be radius, `a` should be the area of the square and `b` should be the area of the circle, the output being `a - b`.

2022-11-29 18:12 UTC, rebornplusplus commented on 1022/bn.md
> +# ক্যাটাগরি : জ্যামিতি
Insert the problem name and number on the first line as well.

2022-11-30 04:07 UTC, walleeva2018 commented
Done sir. Let me Know if anything  is missing

2022-11-30 08:38 UTC, rebornplusplus approved these changes
Looks good to me. Thanks!

2022-11-30 08:38 UTC, merged